# Generated by Django 6.0.3 on 2026-03-28 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0002_department_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.PositiveIntegerField(unique=True)),
                ('type', models.CharField(choices=[('ORQUESTRADOR', 'Orquestrador'), ('AUTOMACAO', 'Automacao')], max_length=20)),
                ('subtype', models.CharField(choices=[('correcao_bug', 'Correção'), ('melhoria', 'Melhoria'), ('nova_funcionalidade', 'Nova Funcionalidade'), ('atualizacao', 'Atualização'), ('novo', 'Novo')], default='correcao_bug', max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url_system', models.URLField(blank=True, null=True)),
                ('steps', models.TextField(blank=True, null=True)),
                ('normal_behavior', models.TextField(blank=True, null=True)),
                ('unexpected_behavior', models.TextField(blank=True, null=True)),
                ('justification', models.TextField(blank=True, null=True)),
                ('acceptance_criteria', models.TextField(blank=True, null=True)),
                ('manual_process', models.TextField(blank=True, null=True)),
                ('automation_name', models.CharField(blank=True, max_length=255, null=True)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_desenvolvimento', 'Em Desenvolvimento'), ('em_producao', 'Em Produção'), ('aguardando_cliente', 'Aguardando Cliente'), ('nao_atendido', 'Não Atendido'), ('fechado', 'Fechado'), ('cancelado', 'Cancelado')], default='aberto', max_length=20)),
                ('notify_by_email', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
            ],
        ),
    ]
