# Generated by Django 6.0.3 on 2026-03-28 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('aberto', 'Aberto'), ('em_desenvolvimento', 'Em Desenvolvimento'), ('em_producao', 'Em Produção'), ('aguardando_cliente', 'Aguardando Cliente'), ('nao_atendido', 'Não Atendido'), ('fechado', 'Fechado'), ('cancelado', 'Cancelado')], max_length=25)),
                ('new_status', models.CharField(choices=[('aberto', 'Aberto'), ('em_desenvolvimento', 'Em Desenvolvimento'), ('em_producao', 'Em Produção'), ('aguardando_cliente', 'Aguardando Cliente'), ('nao_atendido', 'Não Atendido'), ('fechado', 'Fechado'), ('cancelado', 'Cancelado')], max_length=25)),
                ('justification', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket')),
            ],
        ),
    ]
