# Generated by Django 6.0.3 on 2026-03-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticketstatuslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('recebido', 'Recebido'), ('em_desenvolvimento', 'Em Desenvolvimento'), ('em_producao', 'Em Produção'), ('aguardando_cliente', 'Aguardando Cliente'), ('nao_atendido', 'Não Atendido'), ('fechado', 'Fechado'), ('cancelado', 'Cancelado')], default='aberto', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketstatuslog',
            name='new_status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('recebido', 'Recebido'), ('em_desenvolvimento', 'Em Desenvolvimento'), ('em_producao', 'Em Produção'), ('aguardando_cliente', 'Aguardando Cliente'), ('nao_atendido', 'Não Atendido'), ('fechado', 'Fechado'), ('cancelado', 'Cancelado')], max_length=25),
        ),
        migrations.AlterField(
            model_name='ticketstatuslog',
            name='old_status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('recebido', 'Recebido'), ('em_desenvolvimento', 'Em Desenvolvimento'), ('em_producao', 'Em Produção'), ('aguardando_cliente', 'Aguardando Cliente'), ('nao_atendido', 'Não Atendido'), ('fechado', 'Fechado'), ('cancelado', 'Cancelado')], max_length=25),
        ),
    ]
