# Generated by Django 6.0.3 on 2026-04-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_status_alter_ticketstatuslog_new_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('recebido', 'Recebido'), ('em_desenvolvimento', 'Em Desenvolvimento'), ('em_producao', 'Em Produção'), ('aguardando_cliente', 'Aguardando Cliente'), ('fechado', 'Fechado'), ('cancelado', 'Cancelado'), ('nao_atendido', 'Não Atendido')], default='aberto', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('ORQUESTRADOR', 'Orquestrador'), ('AUTOMACAO', 'Automacao'), ('TOC', 'Toc'), ('PLANTAO', 'Plantão')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketstatuslog',
            name='new_status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('recebido', 'Recebido'), ('em_desenvolvimento', 'Em Desenvolvimento'), ('em_producao', 'Em Produção'), ('aguardando_cliente', 'Aguardando Cliente'), ('fechado', 'Fechado'), ('cancelado', 'Cancelado'), ('nao_atendido', 'Não Atendido')], max_length=25),
        ),
        migrations.AlterField(
            model_name='ticketstatuslog',
            name='old_status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('recebido', 'Recebido'), ('em_desenvolvimento', 'Em Desenvolvimento'), ('em_producao', 'Em Produção'), ('aguardando_cliente', 'Aguardando Cliente'), ('fechado', 'Fechado'), ('cancelado', 'Cancelado'), ('nao_atendido', 'Não Atendido')], max_length=25),
        ),
    ]
