name: Deploy TOC

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy
        run: |
          cd /opt/toc
          git pull origin main
          docker compose up -d --build app
          docker compose exec -T app python manage.py migrate --noinput